### ISSUE TITLE
WebP Support 

### ISSUE THREAD

**Issue by haydar** [orangelabweb/imagemagick-engine#14]
Yes JPG is the most used image compression file format but it is not enough for image compression anymore. Google wants to everybody use the modern file format like WebP.  If you don't use WebP file format, Google PageIndex is giving a low score and it affects negatively SEO.

I know ImageMagick allows this but I can't figure out how I can add this support because of I am stranger to Wordpress Code structure.

Can you add this feature? is there any plan?

**Comment by rickardw** [comment]
It's a good idea to have WebP support as it's a image format for the future. Unfortunelly WordPress does not support it yet natively (wonder why) to upload, but that is of course not a huge program since there are many plugins enabling that.

**Comment by rickardw** [comment]
Also see this as reference: https://wordpress.org/support/topic/wordpress-5-8-and-webp/

**Comment by rickardw** [comment]
WebP support has been verified and seems to be working now.

**Comment by haydar** [comment]
> WebP support has been verified and seems to be working now.

Woaw almost 2 years after... Now, i am happy :smile:
