### ISSUE TITLE
add_option [OPTIMIZATION]

### ISSUE THREAD

**Issue by hkodavid** [orangelabweb/imagemagick-engine#28]
Hello,

I suggest a "minimal" optimization.
Use the add_option with autoload yes to avoid one query in every request.
WP has tons of these bad solution and has 50+ unnecessary queries by every request...

**Comment by rickardw** [comment]
Thank you for you suggestion. "Autoload" however loads the options on every WP page and that is not necessary. We use a global variable so per request the options are only loaded once from the database. So not 50+ queries for this plugin.
