### ISSUE TITLE
Uncaught ImagickException: attempt to perform an operation not allowed by the security policy

### ISSUE THREAD

**Issue by Magenstor** [orangelabweb/imagemagick-engine#40]
Hello form Spain,

I have an issue inside Wordpress with Imagemagick Engine, everything with the latest version.

When i try to convert a PDF to image with the next code:
![image](https://user-images.githubusercontent.com/82580166/196957823-3076222b-2fcc-4c19-bfb4-26ec24fd7f04.png)

I get a 500 Internal Server Error at Web and the next code error from the logs:

![image](https://user-images.githubusercontent.com/82580166/196958308-56eb1954-bcc6-4e3e-940b-51b62660525b.png)

I tried almost everything i could, but i detected that the error pop up with the "readImage" command from the Imagemagick Engine.

**Comment by Magenstor** [comment]
Hi @chesio 

Sorry but already tried this idea,i dont have ImageMagick on the /etc folder at my CMS, im using Module PHP directly from ImageMagick Engine

**Comment by chesio** [comment]
> Sorry but already tried this idea,i dont have ImageMagick on the /etc folder at my CMS, im using Module PHP directly from ImageMagick Engine

I believe the PHP module is just a wrapper around the binary, so the policy file as described in SO thread applies to the Imagick PHP module as well. If you can't locate the policy file yourself, you have to talk to your webhost.
